//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.21 at 12:12:38 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://litvak.com/mystore_lesson1/ws/orders", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.litvak.mystore_lesson1.ws.orders;
